#!/usr/bin/env ruby
require 'rally_rest_api'

begin
	config = YAML.load_file("#{Dir.home}/.rallyutils")
rescue 
	puts "\nERROR: #{Dir.home}/.rallyutils not found"
end


rally_user=config["user"]
rally_pass=config["pass"]

puts "Enter Task Name"
task_name = STDIN.gets.chop
user_story = ARGV[0]
puts "Creating task '#{task_name}' in story #{user_story}"

rally = RallyRestAPI.new(:username => rally_user,
			 :password => rally_pass)

stories =  rally.find( :hierarchical_requirement ) { 
					equal :formatted_id , user_story
}

story = stories.first
task = rally.create(:task, :name => task_name , :work_product => story, :estimate => 1)
puts "Task #{task.formatted_i_d} created"
